language: python
os: linux
dist: bionic

python:
  - "3.7"

env:
  - TOX_ENV=py37
  - TOX_ENV=flake8

before_install:
  # Mock Python gi package
  - export PYUSRSITEDIR=$(python -m site --user-site)
  - mkdir -p $PYUSRSITEDIR
  - "echo \"import sys; import mock; sys.modules['gi'] = mock.Mock(); sys.modules['gi.repository'] = mock.Mock(); sys.modules['gi.repository'].Gst.version.side_effect = lambda: (1, 14, 0)\" > ${PYUSRSITEDIR}/usercustomize.py"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py37' ]; then pip install coveralls requests; coveralls; fi"