language: python
sudo: true

python:
  - "3.7"

env:
  - TOX_ENV=py37
  - TOX_ENV=flake8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-gi

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py37' ]; then pip install coveralls requests; coveralls; fi"